OG_GINT_MAPPER = {
    'LocationDetails': {
        "AlignmentID": None,
        "ApprovedBy": None,
        "AssociatedFileReference": None,
        "BingCentroid": None,
        "BitType": 'Bit_Type',
        "CasingHammerDrop": 'Casing_Ham_Fall',
        "CasingHammerWeight": 'Casing_Ham_Wt',
        "CasingID": 'Casing_ID',
        "CasingMethod": 'Casing_method',
        "CasingType": 'Casing_Type',
        "Centroid": None,
        "Chainage": None,
        "CheckedBy": None,
        "CoreID": 'Core_ID',
        "CoreType": 'Core_Type',
        "DateEnd": 'Date_End',
        "DateStart": 'Date_Start',
        "Diameter": None,
        "Driller": 'Driller',
        "DrillMud": 'Drill_Mud',
        "Easting": 'East',
        "EastingTraverseEnd": None,
        "ElevationUncertainty": 'El_Uncertainty',
        "FinalDepth": 'HoleDepth',
        "GridLetterReference": None,
        "GroundLevel": 'Elevation',
        "GroundLevelEnd": None,
        "HammerEfficiency": None,
        "HARepresentative": 'HA_Rep',
        "HoistType": 'Hoist_Type',
        "Latitude": None,
        "LatitudeEnd": None,
        "LatitudeNumeric": None,
        "LocalDatum": None,
        "LocalGridSystem": None,
        "LocalLevel": None,
        "LocalLevelEnd": None,
        "LocalXEnd": None,
        "LocalXGrid": None,
        "LocalYEnd": None,
        "LocalYGrid": None,
        "LocationID": 'PointID',
        "LocationingMethod": None,
        "LocationNote": None,
        "LocationPurpose": None,
        "LoggedBy": None,
        "Longitude": None,
        "LongitudeEnd": None,
        "LongitudeNumeric": None,
        "LongLatCentroid": None,
        "NationalDatumRefSystem": None,
        "Northing": 'North',
        "NorthingTraverseEnd": None,
        "Offset": None,
        "OriginalCompany": None,
        "OriginalId": None,
        "OriginalJobId": None,
        "OriginalLocationID": None,
        "OverburdenDepth": 'Overburden_Depth',
        "Phase": None,
        "PIDModel": 'PID_Model',
        "ProjectionFormat": None,
        "ProtectiveCasingDiameter": None,
        "ProtectiveCasingType": None,
        "RefusalDepth": None,
        "Remarks": None,
        "RockCoredDepth": 'Rock_Cored_Depth',
        "SampleHamFall": 'Sample_Ham_Fall',
        "SampleHamWt": 'Sample_Ham_Wt',
        "SampleID": 'Sample_ID',
        "SampleType": 'Sample_Type',
        "SPTHammerDropHeight": None,
        "SPTHammerWeight": None,
        "SubLocation": 'Location',
        "TerminationReason": None,
        "TestPitLength": None,
        "TestPitWidth": None,
        "Transformation": None,
        "BackfillMethod": None,
        "Contractor": None,
        "CoringMethod": None,
        "DrillingMethod": 'Drilling Method',
        "Equipment": 'Rig_Type',
        "EquipmentType": None,
        "GraphSeriesStyleDefinition": None,
        "HammerType": 'Hammer_Type',
        "HistoricProject": None,
        "LocationAccuracy": None,
        "LocationCluster": None,
        "LocationType": 'Hole Type',
        "NationalGridReferencingSystem": None,
        "Project": None,
        "RefusalType": None,
        "Status": None,
        "TerminationReasonPickList": None,
        "WellCapType": None,
        "Vessel": None,
        "Snapshot": None,
    }
}


"""
'GintRecID': Not applicable
'Name_On_Core_Log': Not applicable
'Number_Samples': Not applicable
'startholedepth': Not applicable
'StartPage': Not applicable
'EndPage': Not applicable
'Plunge' : Not applicable
'Weather': Not applicable
"""